# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3c8b78718613531258bccc72a2b1b390a3f43a14523b47d4341a39228aeca83c9751f243fdd32f4fc0e072c9c778850cb77ce5f3554e1b5584fe44c95ea92ee

test:
  secret_key_base: 976363e784f05fba39e57a7c78167cdcf77343d9d16ca78cb55388538000f7a50d380587ba48427d95026e423b3e56a9bdc3c2ce235cad62118c67423108ee5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
